services:
  tapo-backup:
    container_name: backup
    image: tapobackup
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./scripts:/app/scripts
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - /host_directory:/backup/host_directory:ro
      - /host_directory:/backup/host_directory:ro
    network_mode: host

